version: "3.8"   

services:
  shared-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - video-network   

  view:
    build:
      context: "./services/View/"
    ports:
      - "4002:4002"
    depends_on:
      - shared-db  
    environment:
      PORT: 4002
    networks:
      - video-network   
  
  upload:
    build:
       context: "./services/upload"
    ports:
      - "4003:4003"
    depends_on:
      - shared-db
    environment:
       PORT: 4003
    networks:  
      - video-network
  
  stream:
    build:
        context: "./services/Stream"
    ports:
     - "4004:4004"
    depends_on:
     - shared-db
    environment:
      PORT: 4004
    networks:   
     - video-network

networks:
  video-network:
    driver: bridge
